import { Method } from '../types/methods';

const defaultMethods: Method[] = [
  {
    id: 0,
    name: 'Plain Bob Doubles',
    abbreviation: 'pb5',
    placeNotation: '5.1.5.1.5,125',
    stage: 5,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 1,
    name: 'Plain Bob Minor',
    abbreviation: 'pb6',
    placeNotation: '-16-16-16,12',
    stage: 6,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 2,
    name: 'Plain Bob Triples',
    abbreviation: 'pb7',
    placeNotation: '7.1.7.1.7.1.7.1.7.1.7.1.7.127',
    stage: 7,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 3,
    name: 'Plain Bob Major',
    abbreviation: 'pb8',
    placeNotation: '-18-18-18-18,12',
    stage: 8,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 4,
    name: 'Plain Bob Caters',
    abbreviation: 'pb9',
    placeNotation: '9.1.9.1.9.1.9.1.9.1.9.1.9.1.9.1.9.129',
    stage: 9,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 5,
    name: 'Plain Bob Royal',
    abbreviation: 'pb10',
    placeNotation: '-10-10-10-10-10,12',
    stage: 10,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 6,
    name: 'Plain Bob Cinques',
    abbreviation: 'pb11',
    placeNotation: 'E.1.E.1.E.1.E.1.E.1.E.1.E.1.E.1.E.1.E.1.E.12E',
    stage: 11,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 7,
    name: 'Plain Bob Maximus',
    abbreviation: 'pb12',
    placeNotation: '-1T-1T-1T-1T-1T-1T,12',
    stage: 12,
    defaultBob: 'b',
    defaultSingle: 's',
  },
  {
    id: 8,
    name: 'Stedman Triples',
    abbreviation: 'st7',
    placeNotation: '3.1.7.3.1.3.1.3.7.1.3.1',
    stage: 7,
    defaultBob: 'm',
    defaultSingle: 'n',
  },
  {
    id: 9,
    name: 'Grandsire Triples',
    abbreviation: 'gr7',
    placeNotation: '3.1.7.1.7.1.7.1.7.1.7.1.7.1',
    stage: 7,
    defaultBob: 'g',
    defaultSingle: 'h',
  },
  {
    id: 10,
    name: 'Stedman Caters',
    abbreviation: 'st9',
    placeNotation: '3.1.9.3.1.3.1.3.9.1.3.1',
    stage: 9,
    defaultBob: 'm',
    defaultSingle: 'n',
  },
  {
    id: 11,
    name: 'Grandsire Caters',
    abbreviation: 'gr9',
    placeNotation: '3.1.9.1.9.1.9.1.9.1.9.1.9.1.9.1.9.1',
    stage: 9,
    defaultBob: 'g',
    defaultSingle: 'h',
  },
  {
    id: 12,
    name: 'Stedman Cinques',
    abbreviation: 'st11',
    placeNotation: '3.1.E.3.1.3.1.3.E.1.3.1',
    stage: 11,
    defaultBob: 'm',
    defaultSingle: 'n',
  },
  {
    id: 13,
    name: 'Grandsire Cinques',
    abbreviation: 'gr11',
    placeNotation: '3.1.E.1.E.1.E.1.E.1.E.1.E.1.E.1.E.1.E.1.E.1',
    stage: 11,
    defaultBob: 'g',
    defaultSingle: 'h',
  },
];

export default defaultMethods;
